### ISSUE TITLE
docker-compose.yml with Traefik front end seems to struggle with logging into root:root

### ISSUE THREAD

**Issue by Leopere** [riotkit-org/docker-taiga#2]
Carrying on discussion from over here.  https://github.com/taigaio/taiga-support/issues/35 just looking to be able to plug this thing in behind a reverse proxy to no avail.  Its really quite frustrating when you don't want to have to establish static IP's within your microservices cluster.

**Comment by blackandred** [comment]
Could you share your configuration and describe what is currently, and write what is the expected behavior / goal to achieve?

**Comment by Leopere** [comment]
I will I just need to get time.

**Comment by zicklag** [comment]
This worked for me on Docker Swarm:

https://gist.github.com/zicklag/c69452b872b39561e94077bc71ba8367

**Comment by blackandred** [comment]
Is this still an issue or could I close it?

**Comment by Leopere** [comment]
I haven’t tested it yet but go for it.

**Comment by Leopere** [comment]
Doesn’t work for me with simple docker compose.

**Comment by zicklag** [comment]
If you used my example exactly, you would still need to run Traefik separately and you would need to create the `webgateway` network and put Traefik on it first.

What exactly is the problem you are having?

**Comment by Leopere** [comment]
```BASH
⇒  docker-compose up -d && docker-compose logs -f
taigatest_postgres_1 is up-to-date
Creating taigatest_taiga_1 ...
Creating taigatest_taiga_1 ... done
Attaching to taigatest_taiga_1, taigatest_postgres_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
taiga_1     |  >> Preparing configuration files...
taiga_1     |  HINT: Add your files into /etc/nginx/extensions.d to include them in NGINX configuration
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default timezone ... Etc/UTC
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  |
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | waiting for server to start....2019-08-25 14:57:04.942 UTC [42] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2019-08-25 14:57:05.093 UTC [43] LOG:  database system was shut down at 2019-08-25 14:57:03 UTC
postgres_1  | 2019-08-25 14:57:05.130 UTC [42] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | 2019-08-25 14:57:06.537 UTC [42] LOG:  received fast shutdown request
postgres_1  | waiting for server to shut down....2019-08-25 14:57:06.598 UTC [42] LOG:  aborting any active transactions
postgres_1  | 2019-08-25 14:57:06.600 UTC [42] LOG:  background worker "logical replication launcher" (PID 49) exited with exit code 1
postgres_1  | 2019-08-25 14:57:06.600 UTC [44] LOG:  shutting down
postgres_1  | 2019-08-25 14:57:06.772 UTC [42] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | 2019-08-25 14:57:06.916 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2019-08-25 14:57:06.916 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2019-08-25 14:57:06.966 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2019-08-25 14:57:07.076 UTC [60] LOG:  database system was shut down at 2019-08-25 14:57:06 UTC
postgres_1  | 2019-08-25 14:57:07.113 UTC [1] LOG:  database system is ready to accept connections
taiga_1     |  >> Preparing a database migration
taiga_1     | Running database check
taiga_1     | Connecting to database:
taiga_1     | dbname='taiga' user='taiga' host='postgres' password='dbpassword'
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 35, in <module>
taiga_1     |     conn = connect(conn_string)
taiga_1     |   File "/checkdb.py", line 17, in connect
taiga_1     |     conn = connect(conn_string, retry_num + 1)
taiga_1     |   File "/checkdb.py", line 17, in connect
taiga_1     |     conn = connect(conn_string, retry_num + 1)
taiga_1     |   File "/checkdb.py", line 17, in connect
taiga_1     |     conn = connect(conn_string, retry_num + 1)
taiga_1     |   [Previous line repeated 3 more times]
taiga_1     |   File "/checkdb.py", line 15, in connect
taiga_1     |     raise e
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     | Failed to connect to database server or database does not exist.
taiga_1     | Running database check
taiga_1     | Connecting to database:
taiga_1     | dbname='taiga' user='taiga' host='postgres' password='dbpassword'
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     |
taiga_1     | During handling of the above exception, another exception occurred:
taiga_1     |
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 35, in <module>
taiga_1     |     conn = connect(conn_string)
taiga_1     |   File "/checkdb.py", line 17, in connect
taiga_1     |     conn = connect(conn_string, retry_num + 1)
taiga_1     |   File "/checkdb.py", line 17, in connect
taiga_1     |     conn = connect(conn_string, retry_num + 1)
taiga_1     |   File "/checkdb.py", line 17, in connect
taiga_1     |     conn = connect(conn_string, retry_num + 1)
taiga_1     |   [Previous line repeated 3 more times]
taiga_1     |   File "/checkdb.py", line 15, in connect
taiga_1     |     raise e
taiga_1     |   File "/checkdb.py", line 12, in connect
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
taiga_1     | psycopg2.OperationalError: could not translate host name "postgres" to address: No address associated with hostname
taiga_1     |
taiga_1     | Failed to connect to database server or database does not exist.
taiga_1     | Running database check
```

**Comment by Leopere** [comment]
Nevermind I think it was because I didn't add the `taiga` container to the `- default` network after renaming your `- webgateway` one to `- traefik`

**Comment by Leopere** [comment]
Holy freaking finally!  I finally have an instance of Taiga running after wanting to get a Dockerized instance to play with for 2+ years running behind my Traefik front end.  Now I just need to add some of the plugins somehow...
